package net.seppevdh.natureupdate.datagen;

import net.minecraft.world.item.FlintAndSteelItem;
import net.minecraft.world.level.block.Blocks;
import net.neoforged.neoforge.common.Tags;
import net.neoforged.neoforge.common.data.BlockTagsProvider;
import net.seppevdh.natureupdate.NatureUpdate;
import net.seppevdh.natureupdate.block.ModBlocks;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.tags.BlockTags;
import net.seppevdh.natureupdate.util.ModTags;

import java.util.concurrent.CompletableFuture;

public class ModBlockTagGenerator extends BlockTagsProvider {
    public ModBlockTagGenerator(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider) {
        super(output, lookupProvider, NatureUpdate.MOD_ID);
    }

    @Override
    protected void addTags(HolderLookup.Provider provider) {
        this.tag(BlockTags.MINEABLE_WITH_PICKAXE).add(
                ModBlocks.TIN_BLOCK.get(),
                ModBlocks.BRONZE_BLOCK.get(),
                ModBlocks.TIN_ORE.get(),
                ModBlocks.SMOOTH_STONE_STAIRS.get(),
                ModBlocks.IRON_SLAB.get(),
                ModBlocks.IRON_STAIRS.get(),
                ModBlocks.IRON_GRATE.get(),
                ModBlocks.GOLDEN_DOOR.get(),
                ModBlocks.GOLDEN_TRAPDOOR.get(),
                ModBlocks.GOLDEN_SLAB.get(),
                ModBlocks.GOLDEN_STAIRS.get(),
                ModBlocks.GOLDEN_GRATE.get(),
                ModBlocks.EMERALD_DOOR.get(),
                ModBlocks.EMERALD_TRAPDOOR.get(),
                ModBlocks.EMERALD_SLAB.get(),
                ModBlocks.EMERALD_STAIRS.get(),
                ModBlocks.EMERALD_GRATE.get(),
                ModBlocks.LAPIS_DOOR.get(),
                ModBlocks.LAPIS_TRAPDOOR.get(),
                ModBlocks.LAPIS_SLAB.get(),
                ModBlocks.LAPIS_STAIRS.get(),
                ModBlocks.LAPIS_GRATE.get(),
                ModBlocks.TIN_DOOR.get(),
                ModBlocks.TIN_TRAPDOOR.get(),
                ModBlocks.TIN_SLAB.get(),
                ModBlocks.TIN_STAIRS.get(),
                ModBlocks.TIN_GRATE.get(),
                ModBlocks.BRONZE_DOOR.get(),
                ModBlocks.BRONZE_TRAPDOOR.get(),
                ModBlocks.BRONZE_SLAB.get(),
                ModBlocks.BRONZE_STAIRS.get(),
                ModBlocks.BRONZE_GRATE.get(),
                ModBlocks.DIAMOND_DOOR.get(),
                ModBlocks.DIAMOND_TRAPDOOR.get(),
                ModBlocks.DIAMOND_SLAB.get(),
                ModBlocks.DIAMOND_STAIRS.get(),
                ModBlocks.DIAMOND_GRATE.get(),
                ModBlocks.NETHERITE_DOOR.get(),
                ModBlocks.NETHERITE_TRAPDOOR.get(),
                ModBlocks.NETHERITE_SLAB.get(),
                ModBlocks.NETHERITE_STAIRS.get(),
                ModBlocks.NETHERITE_GRATE.get(),
                ModBlocks.CRAFTING_FURNACE.get(),
                ModBlocks.WATER_BOILER.get(),
                ModBlocks.WOODCUTTER.get(),
                ModBlocks.BREEZING_STAND.get(),
                ModBlocks.END_LANTERN.get()
        );
        this.tag(BlockTags.NEEDS_IRON_TOOL).add(
                ModBlocks.TIN_BLOCK.get(),
                ModBlocks.BRONZE_BLOCK.get(),
                ModBlocks.TIN_ORE.get(),
                ModBlocks.RAW_TIN_BLOCK.get(),
                ModBlocks.GOLDEN_DOOR.get(),
                ModBlocks.GOLDEN_TRAPDOOR.get(),
                ModBlocks.GOLDEN_SLAB.get(),
                ModBlocks.GOLDEN_STAIRS.get(),
                ModBlocks.GOLDEN_GRATE.get(),
                ModBlocks.TIN_DOOR.get(),
                ModBlocks.TIN_TRAPDOOR.get(),
                ModBlocks.TIN_SLAB.get(),
                ModBlocks.TIN_STAIRS.get(),
                ModBlocks.TIN_GRATE.get(),
                ModBlocks.EMERALD_DOOR.get(),
                ModBlocks.EMERALD_TRAPDOOR.get(),
                ModBlocks.EMERALD_SLAB.get(),
                ModBlocks.EMERALD_STAIRS.get(),
                ModBlocks.EMERALD_GRATE.get(),
                ModBlocks.WATER_BOILER.get(),
                ModBlocks.END_LANTERN.get()
        );
        this.tag(BlockTags.NEEDS_STONE_TOOL).add(
                ModBlocks.LAPIS_DOOR.get(),
                ModBlocks.LAPIS_TRAPDOOR.get(),
                ModBlocks.LAPIS_SLAB.get(),
                ModBlocks.LAPIS_STAIRS.get(),
                ModBlocks.LAPIS_GRATE.get(),
                ModBlocks.CRAFTING_FURNACE.get()
        );
        this.tag(BlockTags.MINEABLE_WITH_AXE).add(
                ModBlocks.OAK_MOSAIC.get(),
                ModBlocks.OAK_MOSAIC_STAIRS.get(),
                ModBlocks.OAK_MOSAIC.get(),
                ModBlocks.OAK_TABLE.get(),
                ModBlocks.BIRCH_MOSAIC.get(),
                ModBlocks.BIRCH_MOSAIC_STAIRS.get(),
                ModBlocks.BIRCH_MOSAIC_SLAB.get(),
                ModBlocks.BIRCH_TABLE.get(),
                ModBlocks.SPRUCE_MOSAIC.get(),
                ModBlocks.SPRUCE_MOSAIC_STAIRS.get(),
                ModBlocks.SPRUCE_MOSAIC_SLAB.get(),
                ModBlocks.SPRUCE_TABLE.get(),
                ModBlocks.JUNGLE_MOSAIC.get(),
                ModBlocks.JUNGLE_MOSAIC_STAIRS.get(),
                ModBlocks.JUNGLE_MOSAIC_SLAB.get(),
                ModBlocks.JUNGLE_TABLE.get(),
                ModBlocks.ACACIA_MOSAIC.get(),
                ModBlocks.ACACIA_MOSAIC_STAIRS.get(),
                ModBlocks.ACACIA_MOSAIC_SLAB.get(),
                ModBlocks.ACACIA_TABLE.get(),
                ModBlocks.DARK_OAK_MOSAIC.get(),
                ModBlocks.DARK_OAK_MOSAIC_STAIRS.get(),
                ModBlocks.DARK_OAK_MOSAIC_SLAB.get(),
                ModBlocks.DARK_OAK_TABLE.get(),
                ModBlocks.MANGROVE_MOSAIC.get(),
                ModBlocks.MANGROVE_MOSAIC_STAIRS.get(),
                ModBlocks.MANGROVE_MOSAIC_SLAB.get(),
                ModBlocks.MANGROVE_TABLE.get(),
                ModBlocks.CHERRY_MOSAIC.get(),
                ModBlocks.CHERRY_MOSAIC_STAIRS.get(),
                ModBlocks.CHERRY_MOSAIC_SLAB.get(),
                ModBlocks.CHERRY_TABLE.get(),
                ModBlocks.CRIMSON_MOSAIC.get(),
                ModBlocks.CRIMSON_MOSAIC_STAIRS.get(),
                ModBlocks.CRIMSON_MOSAIC_SLAB.get(),
                ModBlocks.CRIMSON_TABLE.get(),
                ModBlocks.WARPED_MOSAIC.get(),
                ModBlocks.WARPED_MOSAIC_STAIRS.get(),
                ModBlocks.WARPED_MOSAIC_SLAB.get(),
                ModBlocks.WARPED_TABLE.get(),
                ModBlocks.END_CAMPFIRE.get()
        );
        this.tag(BlockTags.NEEDS_IRON_TOOL).remove(
                Blocks.DIAMOND_ORE,
                Blocks.DEEPSLATE_DIAMOND_ORE,
                Blocks.DIAMOND_BLOCK
        );
        this.tag(BlockTags.INCORRECT_FOR_IRON_TOOL).add(
                Blocks.DIAMOND_ORE,
                Blocks.DEEPSLATE_DIAMOND_ORE,
                Blocks.DIAMOND_BLOCK
        );
        this.tag(ModTags.Blocks.NEEDS_BRONZE_TOOL).add(
                Blocks.DIAMOND_ORE,
                Blocks.DEEPSLATE_DIAMOND_ORE,
                Blocks.DIAMOND_BLOCK,
                ModBlocks.DIAMOND_DOOR.get(),
                ModBlocks.DIAMOND_TRAPDOOR.get(),
                ModBlocks.DIAMOND_SLAB.get(),
                ModBlocks.DIAMOND_STAIRS.get(),
                ModBlocks.DIAMOND_GRATE.get()
        );
        this.tag(ModTags.Blocks.NEEDS_BRONZE_TOOL).addTags(BlockTags.NEEDS_IRON_TOOL);
        this.tag(ModTags.Blocks.INCORRECT_FOR_BRONZE_TOOL).addTags(BlockTags.INCORRECT_FOR_IRON_TOOL);
        this.tag(ModTags.Blocks.INCORRECT_FOR_BRONZE_TOOL).remove(ModTags.Blocks.NEEDS_BRONZE_TOOL);
        this.tag(ModTags.Blocks.NEEDS_EMERALD_TOOL).add(
                ModBlocks.BRONZE_DOOR.get(),
                ModBlocks.BRONZE_TRAPDOOR.get(),
                ModBlocks.BRONZE_SLAB.get(),
                ModBlocks.BRONZE_STAIRS.get(),
                ModBlocks.BRONZE_GRATE.get()
        );
        this.tag(ModTags.Blocks.NEEDS_EMERALD_TOOL).addTags(BlockTags.NEEDS_IRON_TOOL);
        this.tag(ModTags.Blocks.INCORRECT_FOR_EMERALD_TOOL).addTags(ModTags.Blocks.INCORRECT_FOR_BRONZE_TOOL).add(
                Blocks.DIAMOND_ORE,
                Blocks.DEEPSLATE_DIAMOND_ORE,
                Blocks.DIAMOND_BLOCK
        );
        this.tag(ModTags.Blocks.INCORRECT_FOR_EMERALD_TOOL).remove(ModTags.Blocks.NEEDS_EMERALD_TOOL);
        this.tag(BlockTags.NEEDS_STONE_TOOL).remove(
                Blocks.IRON_ORE,
                Blocks.DEEPSLATE_IRON_ORE,
                Blocks.IRON_BLOCK,
                Blocks.IRON_DOOR,
                Blocks.IRON_TRAPDOOR
        );
        this.tag(BlockTags.INCORRECT_FOR_STONE_TOOL).add(
                Blocks.IRON_ORE,
                Blocks.DEEPSLATE_IRON_ORE,
                Blocks.IRON_BLOCK,
                Blocks.IRON_DOOR,
                Blocks.IRON_TRAPDOOR,
                ModBlocks.END_LANTERN.get()
        );
        this.tag(ModTags.Blocks.NEEDS_COPPER_TOOL).add(
                Blocks.IRON_ORE,
                Blocks.DEEPSLATE_IRON_ORE,
                Blocks.IRON_BLOCK,
                Blocks.IRON_DOOR,
                Blocks.IRON_TRAPDOOR,
                ModBlocks.IRON_SLAB.get(),
                ModBlocks.IRON_STAIRS.get(),
                ModBlocks.IRON_GRATE.get(),
                ModBlocks.WATER_BOILER.get()
        );
        this.tag(BlockTags.INCORRECT_FOR_WOODEN_TOOL).add(
                ModBlocks.CRAFTING_FURNACE.get(),
                ModBlocks.WATER_BOILER.get()
        );
        this.tag(BlockTags.PLANKS).add(
                ModBlocks.OAK_MOSAIC.get(),
                ModBlocks.BIRCH_MOSAIC.get(),
                ModBlocks.SPRUCE_MOSAIC.get(),
                ModBlocks.ACACIA_MOSAIC.get(),
                ModBlocks.JUNGLE_MOSAIC.get(),
                ModBlocks.DARK_OAK_MOSAIC.get(),
                ModBlocks.MANGROVE_MOSAIC.get(),
                ModBlocks.CHERRY_MOSAIC.get(),
                ModBlocks.PALE_OAK_MOSAIC.get(),
                Blocks.BAMBOO_MOSAIC
        );
        this.tag(BlockTags.WOODEN_STAIRS).add(
                ModBlocks.OAK_MOSAIC_STAIRS.get(),
                ModBlocks.BIRCH_MOSAIC_STAIRS.get(),
                ModBlocks.SPRUCE_MOSAIC_STAIRS.get(),
                ModBlocks.ACACIA_MOSAIC_STAIRS.get(),
                ModBlocks.JUNGLE_MOSAIC_STAIRS.get(),
                ModBlocks.DARK_OAK_MOSAIC_STAIRS.get(),
                ModBlocks.MANGROVE_MOSAIC_STAIRS.get(),
                ModBlocks.CHERRY_MOSAIC_STAIRS.get(),
                ModBlocks.PALE_OAK_MOSAIC_STAIRS.get(),
                Blocks.BAMBOO_MOSAIC_STAIRS
        );
        this.tag(BlockTags.WOODEN_SLABS).add(
                ModBlocks.OAK_MOSAIC_SLAB.get(),
                ModBlocks.BIRCH_MOSAIC_SLAB.get(),
                ModBlocks.SPRUCE_MOSAIC_SLAB.get(),
                ModBlocks.ACACIA_MOSAIC_SLAB.get(),
                ModBlocks.JUNGLE_MOSAIC_SLAB.get(),
                ModBlocks.DARK_OAK_MOSAIC_SLAB.get(),
                ModBlocks.MANGROVE_MOSAIC_SLAB.get(),
                ModBlocks.CHERRY_MOSAIC_SLAB.get(),
                ModBlocks.PALE_OAK_MOSAIC_SLAB.get(),
                Blocks.BAMBOO_MOSAIC_SLAB
        );
        this.tag(BlockTags.NEEDS_DIAMOND_TOOL).add(
                ModBlocks.NETHERITE_DOOR.get(),
                ModBlocks.NETHERITE_TRAPDOOR.get(),
                ModBlocks.NETHERITE_SLAB.get(),
                ModBlocks.NETHERITE_STAIRS.get(),
                ModBlocks.NETHERITE_GRATE.get()
        );
        this.tag(BlockTags.BUTTONS).add(
                ModBlocks.IRON_BUTTON.get(),
                ModBlocks.GOLDEN_BUTTON.get(),
                ModBlocks.DIAMOND_BUTTON.get(),
                ModBlocks.NETHERITE_BUTTON.get(),
                ModBlocks.EMERALD_BUTTON.get(),
                ModBlocks.LAPIS_BUTTON.get(),
                ModBlocks.TIN_BUTTON.get(),
                ModBlocks.BRONZE_BUTTON.get()
        );
        this.tag(BlockTags.STAIRS).add(
                ModBlocks.IRON_STAIRS.get(),
                ModBlocks.GOLDEN_STAIRS.get(),
                ModBlocks.DIAMOND_STAIRS.get(),
                ModBlocks.NETHERITE_STAIRS.get(),
                ModBlocks.EMERALD_STAIRS.get(),
                ModBlocks.LAPIS_STAIRS.get(),
                ModBlocks.TIN_STAIRS.get(),
                ModBlocks.BRONZE_STAIRS.get()
        );
        this.tag(BlockTags.SLABS).add(
                ModBlocks.IRON_SLAB.get(),
                ModBlocks.GOLDEN_SLAB.get(),
                ModBlocks.DIAMOND_SLAB.get(),
                ModBlocks.NETHERITE_SLAB.get(),
                ModBlocks.EMERALD_SLAB.get(),
                ModBlocks.LAPIS_SLAB.get(),
                ModBlocks.TIN_SLAB.get(),
                ModBlocks.BRONZE_SLAB.get()
        );
        this.tag(BlockTags.CROPS).add(
                ModBlocks.OAK_CROP.get(),
                ModBlocks.BIRCH_CROP.get(),
                ModBlocks.SPRUCE_CROP.get(),
                ModBlocks.ACACIA_CROP.get(),
                ModBlocks.JUNGLE_CROP.get(),
                ModBlocks.DARK_OAK_CROP.get(),
                ModBlocks.CHERRY_CROP.get(),
                ModBlocks.RICE_CROP.get(),
                ModBlocks.CORN.get(),
                ModBlocks.RHUBARB.get()
        );
        this.tag(BlockTags.DOORS).add(
                ModBlocks.GOLDEN_DOOR.get(),
                ModBlocks.DIAMOND_DOOR.get(),
                ModBlocks.NETHERITE_DOOR.get(),
                ModBlocks.EMERALD_DOOR.get(),
                ModBlocks.LAPIS_DOOR.get(),
                ModBlocks.TIN_DOOR.get(),
                ModBlocks.BRONZE_DOOR.get()
        );
        this.tag(BlockTags.TRAPDOORS).add(
                ModBlocks.GOLDEN_TRAPDOOR.get(),
                ModBlocks.DIAMOND_TRAPDOOR.get(),
                ModBlocks.NETHERITE_TRAPDOOR.get(),
                ModBlocks.EMERALD_TRAPDOOR.get(),
                ModBlocks.LAPIS_TRAPDOOR.get(),
                ModBlocks.TIN_TRAPDOOR.get(),
                ModBlocks.BRONZE_TRAPDOOR.get()
        );
        this.tag(BlockTags.GUARDED_BY_PIGLINS).add(
                ModBlocks.GOLDEN_DOOR.get(),
                ModBlocks.GOLDEN_TRAPDOOR.get(),
                ModBlocks.GOLDEN_STAIRS.get(),
                ModBlocks.GOLDEN_SLAB.get(),
                ModBlocks.GOLDEN_BUTTON.get()
        );
        this.tag(BlockTags.PRESSURE_PLATES).add(
                ModBlocks.DIAMOND_PRESSURE_PLATE.get(),
                ModBlocks.NETHERITE_PRESSURE_PLATE.get(),
                ModBlocks.EMERALD_PRESSURE_PLATE.get(),
                ModBlocks.LAPIS_PRESSURE_PLATE.get(),
                ModBlocks.TIN_PRESSURE_PLATE.get(),
                ModBlocks.BRONZE_PRESSURE_PLATE.get()
        );
        this.tag(Tags.Blocks.ORE_BEARING_GROUND_STONE).add(
                ModBlocks.TIN_ORE.get()
        );
        this.tag(Tags.Blocks.ORES_IN_GROUND_STONE).add(
                ModBlocks.TIN_ORE.get()
        );
        this.tag(Tags.Blocks.ORES).add(
                ModBlocks.TIN_ORE.get()
        );
        this.tag(ModTags.Blocks.TABLE).add(
                ModBlocks.OAK_TABLE.get(),
                ModBlocks.BIRCH_TABLE.get(),
                ModBlocks.SPRUCE_TABLE.get(),
                ModBlocks.ACACIA_TABLE.get(),
                ModBlocks.JUNGLE_TABLE.get(),
                ModBlocks.DARK_OAK_TABLE.get(),
                ModBlocks.MANGROVE_TABLE.get(),
                ModBlocks.CHERRY_TABLE.get(),
                ModBlocks.BAMBOO_TABLE.get(),
                ModBlocks.PALE_OAK_TABLE.get(),
                ModBlocks.CRIMSON_TABLE.get(),
                ModBlocks.WARPED_TABLE.get()
        );
        this.tag(ModTags.Blocks.END_FIRE_BASE_BLOCKS).add(
                Blocks.PURPUR_BLOCK,
                Blocks.PURPUR_PILLAR
        );
        this.tag(ModTags.Blocks.NORMAL_FUEL_FIRES).add(
                Blocks.FIRE,
                Blocks.CAMPFIRE
        );
        this.tag(ModTags.Blocks.SOUL_FUEL_FIRES).add(
                Blocks.SOUL_FIRE,
                Blocks.SOUL_CAMPFIRE
        );
        this.tag(ModTags.Blocks.END_FUEL_FIRES).add(
                ModBlocks.END_FIRE.get(),
                ModBlocks.END_CAMPFIRE.get()
        );
    }
}