package net.seppevdh.natureupdate.datagen;

import net.minecraft.tags.ItemTags;
import net.minecraft.world.level.block.Blocks;
import net.neoforged.neoforge.common.Tags;
import net.seppevdh.natureupdate.NatureUpdate;
import net.seppevdh.natureupdate.block.ModBlocks;
import net.seppevdh.natureupdate.item.ModItems;
import net.seppevdh.natureupdate.util.ModTags;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.data.tags.ItemTagsProvider;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.Block;

import java.util.concurrent.CompletableFuture;

public class ModItemTagGenerator extends ItemTagsProvider {
    public ModItemTagGenerator(PackOutput packOutput, CompletableFuture<HolderLookup.Provider> completableFuture,
                               CompletableFuture<TagLookup<Block>> lookupCompletableFuture) {
        super(packOutput, completableFuture, lookupCompletableFuture, NatureUpdate.MOD_ID);
    }

    @Override
    protected void addTags(HolderLookup.Provider provider) {
        this.tag(ItemTags.PICKAXES).add(
                ModItems.COPPER_PICKAXE.get(),
                ModItems.BRONZE_PICKAXE.get(),
                ModItems.EMERALD_PICKAXE.get()
        );
        this.tag(ItemTags.AXES).add(
                ModItems.COPPER_AXE.get(),
                ModItems.BRONZE_AXE.get(),
                ModItems.EMERALD_AXE.get()
        );
        this.tag(ItemTags.SHOVELS).add(
                ModItems.COPPER_SHOVEL.get(),
                ModItems.BRONZE_SHOVEL.get(),
                ModItems.EMERALD_SHOVEL.get()
        );
        this.tag(ItemTags.SWORDS).add(
                ModItems.COPPER_SWORD.get(),
                ModItems.BRONZE_SWORD.get(),
                ModItems.EMERALD_SWORD.get()
        );
        this.tag(ItemTags.SWORD_ENCHANTABLE).add(
                ModItems.COPPER_SWORD.get(),
                ModItems.BRONZE_SWORD.get(),
                ModItems.EMERALD_SWORD.get()
        );
        this.tag(ItemTags.HOES).add(
                ModItems.COPPER_HOE.get(),
                ModItems.BRONZE_HOE.get(),
                ModItems.EMERALD_HOE.get()
        );
        this.tag(ItemTags.TRIM_MATERIALS).add(
                ModItems.BRONZE_INGOT.get()
        );
        this.tag(ItemTags.SHARP_WEAPON_ENCHANTABLE).add(
                ModItems.BRONZE_AXE.get(),
                ModItems.BRONZE_SWORD.get(),
                ModItems.COPPER_AXE.get(),
                ModItems.COPPER_SWORD.get(),
                ModItems.EMERALD_AXE.get(),
                ModItems.EMERALD_SWORD.get()
        );
        this.tag(ItemTags.VANISHING_ENCHANTABLE).add(
                ModItems.COPPER_PICKAXE.get(),
                ModItems.BRONZE_PICKAXE.get(),
                ModItems.EMERALD_PICKAXE.get(),
                ModItems.COPPER_AXE.get(),
                ModItems.BRONZE_AXE.get(),
                ModItems.EMERALD_AXE.get(),
                ModItems.COPPER_SHOVEL.get(),
                ModItems.BRONZE_SHOVEL.get(),
                ModItems.EMERALD_SHOVEL.get(),
                ModItems.COPPER_SWORD.get(),
                ModItems.BRONZE_SWORD.get(),
                ModItems.EMERALD_SWORD.get(),
                ModItems.COPPER_HOE.get(),
                ModItems.BRONZE_HOE.get(),
                ModItems.EMERALD_HOE.get(),
                ModItems.COPPER_HELMET.get(),
                ModItems.BRONZE_HELMET.get(),
                ModItems.EMERALD_HELMET.get(),
                ModItems.COPPER_CHESTPLATE.get(),
                ModItems.BRONZE_CHESTPLATE.get(),
                ModItems.EMERALD_CHESTPLATE.get(),
                ModItems.COPPER_LEGGINGS.get(),
                ModItems.BRONZE_LEGGINGS.get(),
                ModItems.EMERALD_LEGGINGS.get(),
                ModItems.COPPER_BOOTS.get(),
                ModItems.BRONZE_BOOTS.get(),
                ModItems.EMERALD_BOOTS.get()
        );
        this.tag(ItemTags.ARMOR_ENCHANTABLE).add(
                ModItems.COPPER_HELMET.get(),
                ModItems.BRONZE_HELMET.get(),
                ModItems.EMERALD_HELMET.get(),
                ModItems.COPPER_CHESTPLATE.get(),
                ModItems.BRONZE_CHESTPLATE.get(),
                ModItems.EMERALD_CHESTPLATE.get(),
                ModItems.COPPER_LEGGINGS.get(),
                ModItems.BRONZE_LEGGINGS.get(),
                ModItems.EMERALD_LEGGINGS.get(),
                ModItems.COPPER_BOOTS.get(),
                ModItems.BRONZE_BOOTS.get(),
                ModItems.EMERALD_BOOTS.get()
        );
        this.tag(Tags.Items.ARMORS).add(
                ModItems.COPPER_HELMET.get(),
                ModItems.BRONZE_HELMET.get(),
                ModItems.EMERALD_HELMET.get(),
                ModItems.COPPER_CHESTPLATE.get(),
                ModItems.BRONZE_CHESTPLATE.get(),
                ModItems.EMERALD_CHESTPLATE.get(),
                ModItems.COPPER_LEGGINGS.get(),
                ModItems.BRONZE_LEGGINGS.get(),
                ModItems.EMERALD_LEGGINGS.get(),
                ModItems.COPPER_BOOTS.get(),
                ModItems.BRONZE_BOOTS.get(),
                ModItems.EMERALD_BOOTS.get()
        );
        this.tag(Tags.Items.CROPS).add(
                ModBlocks.OAK_CROP.get().asItem(),
                ModBlocks.BIRCH_CROP.get().asItem(),
                ModBlocks.SPRUCE_CROP.get().asItem(),
                ModBlocks.ACACIA_CROP.get().asItem(),
                ModBlocks.JUNGLE_CROP.get().asItem(),
                ModBlocks.DARK_OAK_CROP.get().asItem(),
                ModBlocks.CHERRY_CROP.get().asItem(),
                ModBlocks.PALE_OAK_CROP.get().asItem(),
                ModItems.RICE_SEEDS.get(),
                ModBlocks.CORN.get().asItem(),
                ModBlocks.RHUBARB.get().asItem()
        );
        this.tag(Tags.Items.INGOTS).add(
                ModItems.BRONZE_INGOT.get(),
                ModItems.TIN_INGOT.get()
        );
        this.tag(Tags.Items.SEEDS).add(
                ModBlocks.BIRCH_CROP.get().asItem(),
                ModBlocks.ACACIA_CROP.get().asItem(),
                ModBlocks.JUNGLE_CROP.get().asItem(),
                ModBlocks.CHERRY_CROP.get().asItem()
        );
        this.tag(Tags.Items.TOOLS).add(
                ModItems.COPPER_PICKAXE.get(),
                ModItems.BRONZE_PICKAXE.get(),
                ModItems.EMERALD_PICKAXE.get(),
                ModItems.COPPER_AXE.get(),
                ModItems.BRONZE_AXE.get(),
                ModItems.EMERALD_AXE.get(),
                ModItems.COPPER_SHOVEL.get(),
                ModItems.BRONZE_SHOVEL.get(),
                ModItems.EMERALD_SHOVEL.get(),
                ModItems.COPPER_SWORD.get(),
                ModItems.BRONZE_SWORD.get(),
                ModItems.EMERALD_SWORD.get(),
                ModItems.COPPER_HOE.get(),
                ModItems.BRONZE_HOE.get(),
                ModItems.EMERALD_HOE.get()
        );
        this.tag(ItemTags.VILLAGER_PLANTABLE_SEEDS).add(
                ModBlocks.OAK_CROP.get().asItem(),
                ModBlocks.BIRCH_CROP.get().asItem(),
                ModBlocks.SPRUCE_CROP.get().asItem(),
                ModBlocks.ACACIA_CROP.get().asItem(),
                ModBlocks.JUNGLE_CROP.get().asItem(),
                ModBlocks.DARK_OAK_CROP.get().asItem(),
                ModBlocks.CHERRY_CROP.get().asItem(),
                ModBlocks.PALE_OAK_CROP.get().asItem(),
                ModItems.RICE_SEEDS.get(),
                ModBlocks.CORN.get().asItem(),
                ModBlocks.RHUBARB.get().asItem(),
                ModItems.PEAR.get(),
                ModBlocks.STRAWBERRY.get().asItem(),
                ModBlocks.RASPBERRY.get().asItem(),
                ModBlocks.BLACKBERRY.get().asItem()
        );
        this.tag(ItemTags.HEAD_ARMOR).add(
                ModItems.COPPER_HELMET.get(),
                ModItems.BRONZE_HELMET.get(),
                ModItems.EMERALD_HELMET.get()
        );
        this.tag(ItemTags.CHEST_ARMOR).add(
                ModItems.COPPER_CHESTPLATE.get(),
                ModItems.BRONZE_CHESTPLATE.get(),
                ModItems.EMERALD_CHESTPLATE.get()
        );
        this.tag(ItemTags.LEG_ARMOR).add(
                ModItems.COPPER_LEGGINGS.get(),
                ModItems.BRONZE_LEGGINGS.get(),
                ModItems.EMERALD_LEGGINGS.get()
        );
        this.tag(ItemTags.FOOT_ARMOR).add(
                ModItems.COPPER_BOOTS.get(),
                ModItems.BRONZE_BOOTS.get(),
                ModItems.EMERALD_BOOTS.get()
        );
        this.tag(ItemTags.HEAD_ARMOR_ENCHANTABLE).add(
                ModItems.COPPER_HELMET.get(),
                ModItems.BRONZE_HELMET.get(),
                ModItems.EMERALD_HELMET.get()
        );
        this.tag(ItemTags.CHEST_ARMOR_ENCHANTABLE).add(
                ModItems.COPPER_CHESTPLATE.get(),
                ModItems.BRONZE_CHESTPLATE.get(),
                ModItems.EMERALD_CHESTPLATE.get()
        );
        this.tag(ItemTags.LEG_ARMOR_ENCHANTABLE).add(
                ModItems.COPPER_LEGGINGS.get(),
                ModItems.BRONZE_LEGGINGS.get(),
                ModItems.EMERALD_LEGGINGS.get()
        );
        this.tag(ItemTags.FOOT_ARMOR_ENCHANTABLE).add(
                ModItems.COPPER_BOOTS.get(),
                ModItems.BRONZE_BOOTS.get(),
                ModItems.EMERALD_BOOTS.get()
        );
        this.tag(ItemTags.CHICKEN_FOOD).add(
                ModBlocks.BIRCH_CROP.get().asItem(),
                ModBlocks.ACACIA_CROP.get().asItem(),
                ModBlocks.JUNGLE_CROP.get().asItem(),
                ModBlocks.CHERRY_CROP.get().asItem()
        );
        this.tag(ItemTags.DURABILITY_ENCHANTABLE).add(
                ModItems.COPPER_PICKAXE.get(),
                ModItems.BRONZE_PICKAXE.get(),
                ModItems.EMERALD_PICKAXE.get(),
                ModItems.COPPER_AXE.get(),
                ModItems.BRONZE_AXE.get(),
                ModItems.EMERALD_AXE.get(),
                ModItems.COPPER_SHOVEL.get(),
                ModItems.BRONZE_SHOVEL.get(),
                ModItems.EMERALD_SHOVEL.get(),
                ModItems.COPPER_SWORD.get(),
                ModItems.BRONZE_SWORD.get(),
                ModItems.EMERALD_SWORD.get(),
                ModItems.COPPER_HOE.get(),
                ModItems.BRONZE_HOE.get(),
                ModItems.EMERALD_HOE.get(),
                ModItems.COPPER_HELMET.get(),
                ModItems.BRONZE_HELMET.get(),
                ModItems.EMERALD_HELMET.get(),
                ModItems.COPPER_CHESTPLATE.get(),
                ModItems.BRONZE_CHESTPLATE.get(),
                ModItems.EMERALD_CHESTPLATE.get(),
                ModItems.COPPER_LEGGINGS.get(),
                ModItems.BRONZE_LEGGINGS.get(),
                ModItems.EMERALD_LEGGINGS.get(),
                ModItems.COPPER_BOOTS.get(),
                ModItems.BRONZE_BOOTS.get(),
                ModItems.EMERALD_BOOTS.get()
        );
        this.tag(ItemTags.MINING_ENCHANTABLE).add(
                ModItems.COPPER_PICKAXE.get(),
                ModItems.BRONZE_PICKAXE.get(),
                ModItems.EMERALD_PICKAXE.get(),
                ModItems.COPPER_AXE.get(),
                ModItems.BRONZE_AXE.get(),
                ModItems.EMERALD_AXE.get(),
                ModItems.COPPER_SHOVEL.get(),
                ModItems.BRONZE_SHOVEL.get(),
                ModItems.EMERALD_SHOVEL.get(),
                ModItems.COPPER_HOE.get(),
                ModItems.BRONZE_HOE.get(),
                ModItems.EMERALD_HOE.get()
        );
        this.tag(ItemTags.MINING_LOOT_ENCHANTABLE).add(
                ModItems.COPPER_PICKAXE.get(),
                ModItems.BRONZE_PICKAXE.get(),
                ModItems.EMERALD_PICKAXE.get(),
                ModItems.COPPER_AXE.get(),
                ModItems.BRONZE_AXE.get(),
                ModItems.EMERALD_AXE.get(),
                ModItems.COPPER_SHOVEL.get(),
                ModItems.BRONZE_SHOVEL.get(),
                ModItems.EMERALD_SHOVEL.get(),
                ModItems.COPPER_HOE.get(),
                ModItems.BRONZE_HOE.get(),
                ModItems.EMERALD_HOE.get()
        );
        this.tag(ItemTags.EQUIPPABLE_ENCHANTABLE).add(
                ModItems.COPPER_HELMET.get(),
                ModItems.BRONZE_HELMET.get(),
                ModItems.EMERALD_HELMET.get(),
                ModItems.COPPER_CHESTPLATE.get(),
                ModItems.BRONZE_CHESTPLATE.get(),
                ModItems.EMERALD_CHESTPLATE.get(),
                ModItems.COPPER_LEGGINGS.get(),
                ModItems.BRONZE_LEGGINGS.get(),
                ModItems.EMERALD_LEGGINGS.get(),
                ModItems.COPPER_BOOTS.get(),
                ModItems.BRONZE_BOOTS.get(),
                ModItems.EMERALD_BOOTS.get()
        );
        this.tag(ItemTags.PARROT_FOOD).add(
                ModBlocks.BIRCH_CROP.get().asItem(),
                ModBlocks.ACACIA_CROP.get().asItem(),
                ModBlocks.JUNGLE_CROP.get().asItem(),
                ModBlocks.CHERRY_CROP.get().asItem()
        );
        this.tag(ItemTags.PLANKS).add(
                ModBlocks.OAK_MOSAIC.get().asItem(),
                ModBlocks.BIRCH_MOSAIC.get().asItem(),
                ModBlocks.SPRUCE_MOSAIC.get().asItem(),
                ModBlocks.ACACIA_MOSAIC.get().asItem(),
                ModBlocks.JUNGLE_MOSAIC.get().asItem(),
                ModBlocks.DARK_OAK_MOSAIC.get().asItem(),
                ModBlocks.MANGROVE_MOSAIC.get().asItem(),
                ModBlocks.CHERRY_MOSAIC.get().asItem(),
                Items.BAMBOO_MOSAIC,
                ModBlocks.PALE_OAK_MOSAIC.get().asItem(),
                ModBlocks.CRIMSON_MOSAIC.get().asItem(),
                ModBlocks.WARPED_MOSAIC.get().asItem()
        );
        this.tag(ItemTags.STONE_CRAFTING_MATERIALS).add(
                Items.DIORITE,
                Items.GRANITE,
                Items.ANDESITE,
                Items.BASALT,
                Items.END_STONE
        );
        this.tag(ItemTags.STONE_TOOL_MATERIALS).add(
                Items.DIORITE,
                Items.GRANITE,
                Items.ANDESITE,
                Items.BASALT,
                Items.END_STONE
        );
        this.tag(ItemTags.PIGLIN_LOVED).add(
                ModBlocks.GOLDEN_DOOR.get().asItem(),
                ModBlocks.GOLDEN_TRAPDOOR.get().asItem(),
                ModBlocks.GOLDEN_STAIRS.get().asItem(),
                ModBlocks.GOLDEN_SLAB.get().asItem(),
                ModBlocks.GOLDEN_BUTTON.get().asItem()
        );
        this.tag(ModTags.Items.MOSAIC).add(
                ModBlocks.OAK_MOSAIC.get().asItem(),
                ModBlocks.BIRCH_MOSAIC.get().asItem(),
                ModBlocks.SPRUCE_MOSAIC.get().asItem(),
                ModBlocks.ACACIA_MOSAIC.get().asItem(),
                ModBlocks.JUNGLE_MOSAIC.get().asItem(),
                ModBlocks.DARK_OAK_MOSAIC.get().asItem(),
                ModBlocks.MANGROVE_MOSAIC.get().asItem(),
                ModBlocks.CHERRY_MOSAIC.get().asItem(),
                Blocks.BAMBOO_MOSAIC.asItem(),
                ModBlocks.PALE_OAK_MOSAIC.get().asItem(),
                ModBlocks.CRIMSON_MOSAIC.get().asItem(),
                ModBlocks.WARPED_MOSAIC.get().asItem()
        );
        this.tag(ModTags.Items.MOLDS).add(
                ModItems.AXE_MOLD.get(),
                ModItems.PICKAXE_MOLD.get(),
                ModItems.SWORD_MOLD.get(),
                ModItems.SHOVEL_MOLD.get(),
                ModItems.HOE_MOLD.get(),
                ModItems.SAW_MOLD.get(),
                ModItems.SHEARS_MOLD.get(),
                ModItems.SICKLE_MOLD.get(),
                ModItems.HELMET_MOLD.get(),
                ModItems.CHESTPLATE_MOLD.get(),
                ModItems.LEGGINGS_MOLD.get(),
                ModItems.BOOTS_MOLD.get()
        );
        this.tag(ModTags.Items.TABLE).add(
                ModBlocks.OAK_TABLE.get().asItem(),
                ModBlocks.BIRCH_TABLE.get().asItem(),
                ModBlocks.SPRUCE_TABLE.get().asItem(),
                ModBlocks.ACACIA_TABLE.get().asItem(),
                ModBlocks.JUNGLE_TABLE.get().asItem(),
                ModBlocks.DARK_OAK_TABLE.get().asItem(),
                ModBlocks.MANGROVE_TABLE.get().asItem(),
                ModBlocks.CHERRY_TABLE.get().asItem(),
                ModBlocks.BAMBOO_TABLE.get().asItem(),
                ModBlocks.PALE_OAK_TABLE.get().asItem(),
                ModBlocks.CRIMSON_TABLE.get().asItem(),
                ModBlocks.WARPED_TABLE.get().asItem()
        );
        this.tag(ModTags.Items.CHAIR).add(
                ModBlocks.OAK_CHAIR.get().asItem(),
                ModBlocks.BIRCH_CHAIR.get().asItem(),
                ModBlocks.SPRUCE_CHAIR.get().asItem(),
                ModBlocks.ACACIA_CHAIR.get().asItem(),
                ModBlocks.JUNGLE_CHAIR.get().asItem(),
                ModBlocks.DARK_OAK_CHAIR.get().asItem(),
                ModBlocks.MANGROVE_CHAIR.get().asItem(),
                ModBlocks.CHERRY_CHAIR.get().asItem(),
                ModBlocks.BAMBOO_CHAIR.get().asItem(),
                ModBlocks.PALE_OAK_CHAIR.get().asItem(),
                ModBlocks.CRIMSON_CHAIR.get().asItem(),
                ModBlocks.WARPED_CHAIR.get().asItem()
        );
        this.tag(ModTags.Items.BRONZE_REPAIR_INGREDIENT).add(ModItems.BRONZE_INGOT.get());
        this.tag(ModTags.Items.EMERALD_REPAIR_INGREDIENT).add(Items.EMERALD);
        this.tag(ModTags.Items.COPPER_REPAIR_INGREDIENT).add(Items.COPPER_INGOT);
        this.tag(ModTags.Items.SOUL_FUELING).add(ModItems.SOUL_COAL.get());
        this.tag(ModTags.Items.ENDER_FUELING).add(ModItems.ENDER_COAL.get());
        this.tag(ItemTags.WOODEN_SLABS).add(
                ModBlocks.OAK_MOSAIC_SLAB.get().asItem(),
                ModBlocks.BIRCH_MOSAIC_SLAB.get().asItem(),
                ModBlocks.SPRUCE_MOSAIC_SLAB.get().asItem(),
                ModBlocks.ACACIA_MOSAIC_SLAB.get().asItem(),
                ModBlocks.JUNGLE_MOSAIC_SLAB.get().asItem(),
                ModBlocks.DARK_OAK_MOSAIC_SLAB.get().asItem(),
                ModBlocks.MANGROVE_MOSAIC_SLAB.get().asItem(),
                ModBlocks.CHERRY_MOSAIC_SLAB.get().asItem(),
                ModBlocks.PALE_OAK_MOSAIC_SLAB.get().asItem(),
                Items.BAMBOO_MOSAIC_SLAB
        );
        this.tag(ModTags.Items.BREEZING_FUEL).add(
                Items.WIND_CHARGE
        );
    }
}
